// SPDX-License-Identifier: MPL-2.0

#include "Futurewalker.Application.KeyEvent.hpp"

namespace FW_DETAIL_NS
{
///
/// @brief Get key characters.
///
/// Returns characters generated by the key press.
/// This value will be affected by current keyboard layout and modifier keys.
/// This value might include named key string defined in Key class.
///
/// Dead key will always produce Key::Dead and subsequent input can produce composed characters.
/// Modifier or control key will produce named key (e.g. Key::Tab) instead of Unicode control characters (e.g. U+0009 "Horizontal tab").
///
/// For example, pressing Shift+2 on US QWERTY layout will generate '@'.
/// Then switching keyboard layout to Japanese JIS layout and pressing the physical keys, the result will now be '"'.
///
/// Usually this value matches what users intend to input as text.
///
auto KeyEvent::GetKey() const -> String
{
    return _key;
}

///
/// @brief Set key.
///
auto KeyEvent::SetKey(String const& key) -> void
{
    _key = key;
}

///
/// @brief Get key characters before applying modifiers.
///
/// Returns characters which will be generated by pressing the same key without any modifiers applied.
/// This value will be affected by current keyboard layout.
/// This value might include named key string defined in Key class.
///
/// Dead key will always produce Key::Dead.
/// Modifier or control key will produce named key (e.g. Key::Tab) instead of Unicode control characters (e.g. U+0009 "Horizontal tab").
///
/// For example, pressing Shift+Q on US QWERTY layout will generate Key::Q("q").
/// Then switching keyboard layout to French AZERTY layout and pressing same physical keys, the result will now be Key::A("a").
///
/// Usually this value matches characters printed on keycaps of keyboards (assuming keycaps match current keyboard layout).
///
auto KeyEvent::GetUnmodifiedKey() const -> String
{
    return _unmodifiedKey;
}

///
/// @brief Set unmodified key.
///
auto KeyEvent::SetUnmodifiedKey(String const& unmodifiedKey) -> void
{
    _unmodifiedKey = unmodifiedKey;
}

///
/// @brief Get timestamp.
///
auto KeyEvent::GetTimestamp() const -> MonotonicTime
{
    return _timestamp;
}

///
/// @brief Set timestamp.
///
auto KeyEvent::SetTimestamp(MonotonicTime const timestamp) -> void
{
    _timestamp = timestamp;
}

///
/// @brief Get whether the key event is generated during IME composition.
///
auto KeyEvent::IsComposing() const -> Bool
{
    return _composing;
}

///
/// @brief Set whether the key event is generated during IME composition.
///
auto KeyEvent::SetComposing(Bool const composing) -> void
{
    _composing = composing;
}

///
/// @brief Get text value.
///
auto KeyEvent::Down::GetText() const -> String
{
    return _text;
}

///
/// @brief Set text value.
///
auto KeyEvent::Down::SetText(String const& text) -> void
{
    _text = text;
}

///
/// @brief Get modifier keys.
///
auto KeyEvent::Down::GetModifiers() const -> Flags<ModifierKeyFlag>
{
    return _modifiers;
}

///
/// @brief Set modifier keys.
///
auto KeyEvent::Down::SetModifiers(Flags<ModifierKeyFlag> const modifiers) -> void
{
    _modifiers = modifiers;
}

///
/// @brief Get repeat status.
///
auto KeyEvent::Down::IsRepeat() const -> Bool
{
    return _repeat;
}

///
/// @brief Set repeat status.
///
auto KeyEvent::Down::SetRepeat(Bool const repeat) -> void
{
    _repeat = repeat;
}
}
