name: main
run-name: main
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      profile:
        required: true
        type: string
jobs:
  build-main:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run:  conan build . -pr:b=default -pr:h=${{ inputs.profile }} --build=missing
