name: main
run-name: main
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      profile:
        required: true
        type: string
jobs:
  build-main:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Checkout latest Conan
        uses: actions/checkout@v4
        with:
          repository: 'conan-io/conan'
          path: 'conan-io'
          ref: 'develop2'
      - name: Install Conan
        run: pip install -e ./conan-io
      - name: Display Conan version
        run: conan --version
      - name: Detect default profile
        run: conan profile detect
      - name: Checkout Skia recipe
        uses: actions/checkout@v4
        with:
          repository: 'mocabe/conan-skia'
          path: 'conan-skia'
          refn: 'main'
      - name: Add Skia recipe to Conan
        run: conan remote add conan_skia ./conan-skia
      - name: Build
        run:  conan build . -pr:b=default -pr:h=${{ inputs.profile }} --build=missing
