name: windows-latest
run-name: windows-latest
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: winget install --source winget --exact --id Microsoft.WindowsSDK.10.0.22621
      - uses: ./.github/workflows/main.yml
        with:
          profile: ./conan/vs2022_x86_64_Debug.profile
